feat(walls): enhanced setting wallpaper script

diff --git a/bin/.config/bin/walls b/bin/.config/bin/walls
--- a/bin/.config/bin/walls
+++ b/bin/.config/bin/walls
@@ -1,9 +1,43 @@
 #!/usr/bin/env bash
 
+random_wallpaper() {
+    find ~/Desktop/Github/wallpapers -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.*" \) | grep -iE '\.(jpg|png)$' | shuf -n1
+}
+
+select_wallpaper() {
+    find ~/Desktop/Github/wallpapers -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.*" \) | grep -iE '\.(jpg|png)$' | fzf --preview='ueberzug tmux {}'
+}
+
 if [[ $# -eq 1 ]]; then
-    selected=$1
+    case $1 in
+    r)
+        selected=$(random_wallpaper)
+        feh --bg-scale "$selected" &
+        ;;
+    s)
+        selected=$(select_wallpaper)
+        feh --bg-scale "$selected" &
+        ;;
+    *)
+        echo "Invalid option: $1"
+        echo "Usage: $0 [r|s]"
+        exit 1
+        ;;
+    esac
 else
-    selected=$(find ~/Desktop/Github/wallpapers -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.*" \) | grep -iE '\.(jpg|png)$' | fzf)
+    selected=$(echo -e "random\nselection" | fzf)
+
+    case $selected in
+    random)
+        selected=$(random_wallpaper)
+        feh --bg-scale "$selected" &
+        ;;
+    selection)
+        selected=$(select_wallpaper)
+        feh --bg-scale "$selected" &
+        ;;
+    *) exit 0 ;;
+    esac
 fi
 
 if [[ -z $selected ]]; then
